[package]
name = "madhava-gather"
version = "0.1.0"
authors = ["jb-asi <jburnett@appliedsystems.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/" }
num-format = { version = "0.4", features = ["with-system-locale"] }
num_cpus = "1"